name: stale

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    # At 08:00 on every day-of-week from Monday through Friday.
    - cron: "0 8 * * 1-5"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
